version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=monitoraprecos
      - POSTGRES_USER=monitoraprecos
      - POSTGRES_PASSWORD=senha_segura
    ports:
      - "5432:5432"

volumes:
  postgres_data: