# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(
                choices=[('cliente', 'Produto do Cliente'), ('concorrente', 'Produto de Concorrente')],
                default='concorrente',
                max_length=20,
                verbose_name='Tipo do Produto'
            ),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_cliente',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Preço do Cliente'
            ),
        ),
    ]